Unload darshan-runtime in Frontier script
glotzerlab/software pull request #297
Opened 2023-05-16 17:36 UTC by b-butler

Removes the darshan-runtime from the module list in Frontier's environment.sh file.

2023-05-16 18:32 UTC, DomFijan commented
Maybe also add unload darshan to summit script as well?

2023-05-17 13:11 UTC, joaander requested changes

2023-05-17 13:11 UTC, joaander commented on script/frontier/install.sh
> +module unload darshan-runtime/3.4.0
```suggestion
module unload darshan-runtime
```
Handle future cases when the default `darshan-runtime` is a different version.

Also, move this change to `frontier.jinja` (and as Dom suggested, `summit.jinja`). `install.sh` will be overwritten when `make_dockerfiles.py` is executed.

2023-05-17 14:51 UTC, joaander approved these changes
Thanks!

2023-05-17 14:52 UTC, merged